[package]
name = "revvy02/slick"
description = "Roblox Luau state management library"
version = "2.0.0"
license = "MIT"
authors = ["revvy02"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
Cleaner = "revvy02/cleaner@1.0.0"
TrueSignal = "revvy02/truesignal@1.0.1"
TestEZ = "roblox/testez@0.4.1"
